trigger:
  branches:
    include:
    - main
  tags:
    include:
    - v*

strategy:
  matrix:
    windows:
      imageName: 'windows-latest'
    linux:
      imageName: 'ubuntu-latest'
    macos:
      imageName: 'macOS-latest'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Installing packages"
    npm install
  displayName: Install Node Packages

- bash: |
    echo ">>> Compile vscode-test"
    npm run compile
    echo ">>> Compiled vscode-test"
    echo ">>> Run sample integration test"
    npm run test
  displayName: Run Tests

- bash: |
    echo ">>> Publish"
    npm run deploy
  displayName: Publish
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), eq(variables['Agent.OS'], 'Linux'))
  env:
    VSCE_PAT: $(VSCE_PAT)
    DISPLAY: ':99.0'